//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialUsuarioTickets
    {
        public System.Guid IdHistorial { get; set; }
        public System.Guid IdUsuario { get; set; }
        public System.Guid IdSubCategoria { get; set; }
    
        public virtual SubCategorias SubCategorias { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
