//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSTickets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TicketsEntities : DbContext
    {
        public TicketsEntities()
            : base("name=TicketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<HistorialUsuarioTickets> HistorialUsuarioTickets { get; set; }
        public virtual DbSet<SubCategorias> SubCategorias { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int spInsCategoria(Nullable<System.Guid> idCategoria, string nombre, string descripcion, string urlImage)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(System.Guid));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var urlImageParameter = urlImage != null ?
                new ObjectParameter("UrlImage", urlImage) :
                new ObjectParameter("UrlImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsCategoria", idCategoriaParameter, nombreParameter, descripcionParameter, urlImageParameter);
        }
    
        public virtual int spInsertUsuario(string nombre, string apellidos, string sexo, string correo, string contrasena, string tipoLogin, string urlImage)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var tipoLoginParameter = tipoLogin != null ?
                new ObjectParameter("TipoLogin", tipoLogin) :
                new ObjectParameter("TipoLogin", typeof(string));
    
            var urlImageParameter = urlImage != null ?
                new ObjectParameter("UrlImage", urlImage) :
                new ObjectParameter("UrlImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertUsuario", nombreParameter, apellidosParameter, sexoParameter, correoParameter, contrasenaParameter, tipoLoginParameter, urlImageParameter);
        }
    
        public virtual int spInsHistorialUsuario(Nullable<System.Guid> idUsuario, Nullable<System.Guid> idSubCategoria)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(System.Guid));
    
            var idSubCategoriaParameter = idSubCategoria.HasValue ?
                new ObjectParameter("IdSubCategoria", idSubCategoria) :
                new ObjectParameter("IdSubCategoria", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsHistorialUsuario", idUsuarioParameter, idSubCategoriaParameter);
        }
    
        public virtual int spInsSubCategoria(Nullable<System.Guid> idCategoria, string nombre, string descripcion, string urlImage, Nullable<decimal> precioNormal, Nullable<decimal> precioDescuento, Nullable<int> codigoDescuento)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(System.Guid));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var urlImageParameter = urlImage != null ?
                new ObjectParameter("UrlImage", urlImage) :
                new ObjectParameter("UrlImage", typeof(string));
    
            var precioNormalParameter = precioNormal.HasValue ?
                new ObjectParameter("PrecioNormal", precioNormal) :
                new ObjectParameter("PrecioNormal", typeof(decimal));
    
            var precioDescuentoParameter = precioDescuento.HasValue ?
                new ObjectParameter("PrecioDescuento", precioDescuento) :
                new ObjectParameter("PrecioDescuento", typeof(decimal));
    
            var codigoDescuentoParameter = codigoDescuento.HasValue ?
                new ObjectParameter("CodigoDescuento", codigoDescuento) :
                new ObjectParameter("CodigoDescuento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsSubCategoria", idCategoriaParameter, nombreParameter, descripcionParameter, urlImageParameter, precioNormalParameter, precioDescuentoParameter, codigoDescuentoParameter);
        }
    
        public virtual ObjectResult<spSelCategorias_Result> spSelCategorias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelCategorias_Result>("spSelCategorias");
        }
    
        public virtual ObjectResult<spSelHistorialUsuario_Result> spSelHistorialUsuario(Nullable<System.Guid> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("IdUsuario", idUsuario) :
                new ObjectParameter("IdUsuario", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelHistorialUsuario_Result>("spSelHistorialUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<spSelSubCategorias_Result> spSelSubCategorias(Nullable<System.Guid> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelSubCategorias_Result>("spSelSubCategorias", idCategoriaParameter);
        }
    
        public virtual ObjectResult<spSelUsuario_Result> spSelUsuario(string correo, string contrasena)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelUsuario_Result>("spSelUsuario", correoParameter, contrasenaParameter);
        }
    
        public virtual int spUpdateUsuario(Nullable<System.Guid> idUsaurio, string nombre, string apellidos, string sexo, string correo, string contrasena, string tipoLogin, string urlImage)
        {
            var idUsaurioParameter = idUsaurio.HasValue ?
                new ObjectParameter("IdUsaurio", idUsaurio) :
                new ObjectParameter("IdUsaurio", typeof(System.Guid));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var tipoLoginParameter = tipoLogin != null ?
                new ObjectParameter("TipoLogin", tipoLogin) :
                new ObjectParameter("TipoLogin", typeof(string));
    
            var urlImageParameter = urlImage != null ?
                new ObjectParameter("UrlImage", urlImage) :
                new ObjectParameter("UrlImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateUsuario", idUsaurioParameter, nombreParameter, apellidosParameter, sexoParameter, correoParameter, contrasenaParameter, tipoLoginParameter, urlImageParameter);
        }
    }
}
